### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by baj12** [aggarwalankush/ionic2-mosum#1]
Hi, 
very interesting project!!!1

I am currently trying to compile it on a mac. I ran into a problem with missing ionic-app-scripts
that led me also install:
@ionic/app-scripts@latest --save-dev

Now I have the impression that ionic-app-scripts is made for ionic 1 not 2... 

I get the error message that module 'typescript' is not found...

Could you please enlighten me if ionic-app-scripts is needed and which version? Also does the error message ? it occurs in module.js:422 (when ionic-app-scripts build is called/ as a result of  "ionic build android."

Thx for your support,

Bernd

**Comment by aggarwalankush** [comment]
ionic-app-scripts and typescript are mentioned in devDependencies in [package.json](https://github.com/aggarwalankush/ionic2-mosum/blob/master/package.json#L28) When you clone the project and do `npm install`, it should install all devDependencies as well. If for some reason it doesn't run following command to download it manually:

```bash
npm install @ionic/app-scripts@0.0.47 typescript@2.0.9 @types/googlemaps@3.25.36 @types/lodash@4.14.38 @types/moment-timezone@0.2.32
```

Closing as repo has been updated to ionic rc4 with more fixes. Try above solution and feel free to reopen if doesn't work.

**Comment by baj12** [comment]
Hi, sorry for the late responds... I still wanted to thank you for your support!!!
B
