### ISSUE TITLE
ERR File Not Found android_assest/www/index.html

### ISSUE THREAD

**Issue by manas89** [aggarwalankush/ionic2-mosum#3]
I am following same instruction as given and getting file not found ERR....**android_assest/www/index.html**

I think in ionic www folder must contain **index.html** but in your case its not there...

Please Help.

**Comment by aggarwalankush** [comment]
Make sure you have updated node and npm version as mentioned in https://github.com/aggarwalankush/ionic2-mosum#prerequisites. I just cloned repo and did `npm install` and it's working. try `ionic serve` to run in browser and see if it's working.

**Comment by manas89** [comment]
Node Verison - v6.10.2
NPM Version - 3.10.10

I cloned repo the run npm install all the packages installed successfully.

when run ionic serve getting this error in browser

 Error: ENOENT: no such file or directory, open 'D:\Personal\Personal\applications\myapp\weather\ionic2-mosum\www\index.html'

Ionic 1 is globally installed in my system does it make any difference...?? Do i need to update that also ??

**Comment by manas89** [comment]
As per my knowledge when we run **ionic serve** it host index page from **www** folder but in repo there is no **index.html** its in src folder...does this make any difference. ??

**Comment by aggarwalankush** [comment]
You don't require anything in www folder, everything is automatically generated by ionic. try `npm uninstall -g ionic cordova` and then `npm install -g ionic cordova`. Here is the ionic info in my system, make sure your cordova and ionic cli version matches.

```bash
ionic2-mosum$ ionic info

Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.3.0
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by manas89** [comment]
Thanks this worked for me..issue is I have old version on Ionic(1.7) installed globally on my system.

Now I  have same version as you have.

But I am getting this error when run ionic serve.

![err](https://cloud.githubusercontent.com/assets/8168234/25150007/20e87fc6-249e-11e7-9d51-fdef6fc15486.jpg)

**Comment by aggarwalankush** [comment]
Try running 
```
npm install @types/googlemaps@3.26.8 @types/lodash@4.14.61 @types/moment-timezone@0.2.34
```
 These are the dev dependencies mentioned here https://github.com/aggarwalankush/ionic2-mosum/blob/master/package.json#L34. Should install by default but seems like didn't install in your case.

**Comment by manas89** [comment]
I have node verison 6 installed and as per your specs i have updated to latest version 7.9.0

And run ionic serve getting this error...

![err](https://cloud.githubusercontent.com/assets/8168234/25162892/b5cf845a-24e3-11e7-9836-f97160a9c7ee.jpg)

Can you share your skype/hangout id we can have screen share session.

**Comment by aggarwalankush** [comment]
As error is stating, can you delete node_modules folder and do following -
```bash
npm install
npm rebuild node-sass
npm install @types/googlemaps@3.26.8 @types/lodash@4.14.61 @types/moment-timezone@0.2.34
ionic serve
```

**Comment by manas89** [comment]
I followed same steps.

I am still getting previous error **cannot find name 'google'** in src>pages>location.ts

![err](https://cloud.githubusercontent.com/assets/8168234/25198584/a6afa1ee-2565-11e7-9c2e-071ce07353d7.jpg)

**Comment by aggarwalankush** [comment]
`npm install -D @types/googlemaps` should work.

**Comment by manas89** [comment]
Still same error persists **Cannot find name 'google'.** after `npm install -D @types/googlemaps`

![err](https://cloud.githubusercontent.com/assets/8168234/25210677/c61dd47c-259e-11e7-84e3-791e64e362f6.jpg)

**Comment by aggarwalankush** [comment]
I just pushed some changes related to typing errors. Try following and it should work.

1. Pull the latest code from this repo
2. Delete node_modules folder
3. Run following commands
```
$ npm install
$ npm install --only=dev
```

If it doesn't work, run `ionic info` from a terminal/cmd prompt and paste output below.

**Comment by manas89** [comment]
Working perfectly fine now.

Thanks for your support.
