### ISSUE TITLE
Renaming project to ionic-mosum, app files to just Ionic

### ISSUE THREAD

**Issue by jamzi** [aggarwalankush/ionic2-mosum#5]
Ionic now uses semver (https://twitter.com/maxlynch/status/846372207601201152), so I was thinking we can rename everything from Ionic 2 -> Ionic. 

I can prepare branch and rename everything inside the app. You could rename the repo name if it seems reasonable to you (https://help.github.com/articles/renaming-a-repository/).

**Comment by aggarwalankush** [comment]
I think we can wait on this for some time. As most people are still referring to the newer version as Ionic 2.
